// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package position_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category int32

const (
	Category_Novel     Category = 0
	Category_SciFi     Category = 1
	Category_Fantastic Category = 2
	Category_Spiritual Category = 3
)

var Category_name = map[int32]string{
	0: "Novel",
	1: "SciFi",
	2: "Fantastic",
	3: "Spiritual",
}

var Category_value = map[string]int32{
	"Novel":     0,
	"SciFi":     1,
	"Fantastic": 2,
	"Spiritual": 3,
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

type Book struct {
	ID                   int32     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Author               []*Author `protobuf:"bytes,3,rep,name=Author,proto3" json:"Author,omitempty"`
	Category             Category  `protobuf:"varint,4,opt,name=Category,proto3,enum=genproto.Category" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() []*Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_Novel
}

type Author struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("genproto.Category", Category_name, Category_value)
	proto.RegisterType((*Book)(nil), "genproto.Book")
	proto.RegisterType((*Author)(nil), "genproto.Author")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0xdd, 0xbb, 0x4b, 0xc8, 0x8d, 0x1a, 0x96, 0xa9, 0x4e, 0x6c, 0x8e, 0x54, 0x8b, 0xc8,
	0x09, 0xb1, 0x17, 0x8c, 0x21, 0x90, 0x26, 0xc5, 0xa5, 0xb3, 0x91, 0xf5, 0x58, 0xe2, 0x60, 0xdc,
	0x59, 0x76, 0x37, 0x01, 0x7b, 0x7f, 0xb8, 0xe4, 0x74, 0xbd, 0xd6, 0xee, 0x9b, 0x79, 0x8f, 0x8f,
	0x07, 0x17, 0xce, 0xf8, 0xc0, 0xb6, 0x71, 0x9e, 0x23, 0xe3, 0x64, 0x67, 0x6c, 0x4f, 0xb3, 0x2f,
	0x01, 0xc5, 0x82, 0xf9, 0x1d, 0xa7, 0x90, 0xad, 0x97, 0x95, 0xa8, 0x85, 0x1a, 0xb5, 0xd9, 0x7a,
	0x89, 0x08, 0xc5, 0x46, 0x7f, 0x98, 0x2a, 0xab, 0x85, 0x2a, 0xdb, 0x9e, 0x51, 0xc1, 0xf8, 0xf1,
	0x10, 0xdf, 0xd8, 0x57, 0x79, 0x9d, 0xab, 0xf3, 0xb9, 0x6c, 0x92, 0xa7, 0xf9, 0xf9, 0xb7, 0xbf,
	0x39, 0x36, 0x30, 0x79, 0xd2, 0xd1, 0xec, 0xd8, 0x7f, 0x56, 0x45, 0x2d, 0xd4, 0x74, 0x8e, 0x43,
	0x37, 0x25, 0xed, 0x5f, 0x67, 0x76, 0x9b, 0xcc, 0xff, 0xd9, 0x71, 0xf3, 0x30, 0xd8, 0xb1, 0x84,
	0xd1, 0x86, 0x8f, 0x66, 0x2f, 0xcf, 0x4e, 0xb8, 0xed, 0x68, 0x45, 0x52, 0xe0, 0x25, 0x94, 0x2b,
	0x6d, 0xa3, 0x0e, 0x91, 0x3a, 0x99, 0x9d, 0xce, 0xad, 0x23, 0x4f, 0xf1, 0xa0, 0xf7, 0x32, 0x5f,
	0x5c, 0x3f, 0x5f, 0xa5, 0x31, 0x77, 0x8e, 0x03, 0x45, 0x62, 0xfb, 0x12, 0x8c, 0x3f, 0x52, 0x67,
	0x5e, 0xc7, 0xfd, 0xff, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x29, 0x00, 0xdd, 0x32, 0x01,
	0x00, 0x00,
}
